apiVersion:  v1
kind: Secret
metadata:
  name: app-secret

data:  #here data is in plain text
  DB_Host: mysql
  DB_User: root
  DB_Password: passwrd

#we must specify secret data in encoded format

#convert text in linux
# echo -n 'mysql' | base64
# echo -n 'root' | base64
# echo -n 'passwrd' | base64

# Decode 

#echo -n 'bxlzcWw=' | base64 --decode